repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-json
    - id: check-toml
    - id: check-xml
    - id: check-yaml
    - id: debug-statements
    - id: check-builtin-literals
    - id: check-case-conflict
    - id: check-docstring-first
    - id: detect-private-key
      exclude: ^tests/fixtures/
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
